Created Tribute
ceddddy/A-Tribute-Page pull request #1
Opened 2023-01-16 19:17 UTC by ceddddy

# In this branch we :
- Added linters
- Added node modules
- Added html and css files
- Added tribute information

2023-01-16 19:29 UTC, ceddddy commented
Please check your linters. You have got linter errors. 

file:///home/cedy/Pictures/Screenshots/Screenshot%20from%202023-01-16%2021-25-39.png

You can use the following command to check for errors in your terminal :  npx stylelint "**/*.{css,scss}"

2023-01-16 22:12 UTC, ceddddy reviewed
You have done a great job so far. Please add a README to your project & make the changes  requested below and you will be ready to merge into your main branch.

2023-01-16 22:12 UTC, ceddddy commented on index.html
> +      <h1 id="title">Dr. Norman Borlaug</h1>
Please wrap your heading-one element within a header element for semantic reasons.

2023-01-16 22:12 UTC, ceddddy commented on index.html
> +        <p id="img-caption">The man who saved a billion lives</p>
You are doing great so far. Please consider replacing the paragraph tag with a heading tag (e.g h2, h3, h4, h5 etc).

2023-01-16 22:46 UTC, osamaashraf6 requested changes
Hi @ceddddy 😊, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![AlonzoLeroneThisCloseGIF](https://user-images.githubusercontent.com/83360636/212667901-8bd5bd32-5e62-4aeb-85a6-0a6ab21d8109.gif)

## Highlights👍

- [ ] Great job at using the inline comments💯
- [ ] Used at least two inline comments✔️
- [ ] Polite comments✔️

## Required Changes ♻️


- [ ]  I see 😃 that you put two comments before the comment at code, so the comment before code is called review summary and we put one summary I see that you commented for the linter after that you solved it after that you💯 commented again, so please 😊 in the next time at your reviews try to give one summary and after summary put the comments at code and the required changes things which not having comment at code like commit I put them here in the review summary ♻️, so with that, you will achieve GitHub features for reviews😊


_Check the comments under the review._

## Optional suggestions
- [ ]  Try to mention the name of the student up the review and the  Highlights👍for the student like Descriptive pull request etc... to make him/her feel that he/she did well on the project😃 , please take a look at mine here to understand I mentioned here the Highlights for you after that I mentioned the  Required Changes, so with that, your review will be great. 😃


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-16 22:46 UTC, osamaashraf6 commented on index.html
> +        <p id="img-caption">The man who saved a billion lives</p>
> You are doing great so far. Please consider replacing the paragraph tag with a heading tag (e.g h2, h3, h4, h5, etc).

- [ ] Great job 😃at replying to the comments, but I see that you told the student to replace the paragraph tag with a heading tag..... without explaining why to do this change, so kindly 😊 try to explain to the student why should he/her change this part because this clear to you, but not clear to him/her.💯for example as you made up you did well 👌 at the first comment you told the student
 ``` to wrap the heading-one element within a header element you told the student here the reason is for a semantic reason```, so that's great, so kindly try to mention every time you review the reason for the change because it is obvious to you and not obvious to the student👌

2023-01-17 09:51 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @ceddddy, 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://media.tenor.com/96GqZ1hf48sAAAAM/approved-touge.gif" width="500px">

## Good Points 👍

- Has a proper Pull Request. ✔️
- No Linter errors ✔️
- Good use of Github flow ✔️

## Optional changes

- [Optional] I would kindly suggest you make use of a friendly gif and emojis in your review as this gives your review a kind of friendly attraction to the author of the project you are reviewing.

- [Optional] I would suggest you make use of a general review the way reviewers use to leave it in your project. like the one that I used.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 10:38 UTC, merged